version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing nodejs...
      - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      - apt-get install -y nodejs
      - echo Installing npm...
      - apt-get install -y npm
      - echo Installing project dependencies...
      - cd frontend
      - npm install
      - echo Building React app...
      - npm run build
      - cd ..
  build:
    commands:
      - echo Installing Python dependencies...
      - pip install -r requirements.txt pylint
      - echo Running Django migrations...
      - python manage.py migrate
artifacts:
  files:
    - '**/*'
